TARGET:=
FUNC:=
HF:=
#TARGETに作成したい実行ファイル名 
#FUNCに各種関数定義など
#HFに.hファイル名
#ヘッダファイルは.hまで打て

CC:=gcc
LDFLAGS:=-lm


OBJ:=$(TARGET:%=%.o)
FOBJ:=$(FUNC:%=%.o)
.PHONY:all clean
all:$(TARGET)

define template
$(1):$(1).o $(FOBJ)
	$(CC) $(LDFLAGS) -o $1 $(1).o $(FOBJ)

$(1).o:$(1).c $(HF)
	$(CC) -c $(1).c

endef

define genobj
$(1).o:$(1).c $(HF)
	$(CC) -c $(1).c

endef

$(foreach x,$(TARGET),$(eval $(call template,$(x))))
$(foreach x,$(FUNC),$(eval $(call genobj,$(x))))

clean:
	rm -rf $(TARGET) $(OBJ)
